# Generated by Django 3.0.5 on 2020-10-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbername', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='barberAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(upload_to='images/')),
                ('username', models.CharField(max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=1000)),
                ('employee_no', models.PositiveIntegerField()),
                ('About', models.TextField(max_length=1000)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='userAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(upload_to='images/')),
                ('username', models.CharField(max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=1000)),
                ('About', models.TextField(max_length=1000)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
