# Generated by Django 3.0.5 on 2020-09-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barberAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(upload_to='')),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('street_address', models.CharField(max_length=64)),
                ('pincode', models.IntegerField()),
                ('employee_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(upload_to='')),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('street_address', models.CharField(max_length=64)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
