# Generated by Django 3.0.5 on 2020-09-05 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberaddress',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
