# Generated by Django 3.0.5 on 2020-10-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0002_auto_20201024_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberaddress',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='name',
        ),
    ]
