# Generated by Django 3.0.5 on 2020-09-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0002_auto_20200905_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberaddress',
            name='dp',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='dp',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
