# Generated by Django 3.0.5 on 2020-09-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0003_auto_20200906_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbername', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
