# Generated by Django 3.0.5 on 2020-09-11 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0004_appointmentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberaddress',
            name='About',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barberaddress',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='About',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
